import React from 'react';
import { Layout } from '../components/Layout';
import { Link } from 'react-router-dom';
function Privacypolicy() {
	return (
		<Layout>
			<div className='container' style={{ marginBlock: '150px' }}>
				<h1>Privacy Policy</h1>
				<small>Last updated: April 20, 2022</small>
				<small>
					This Privacy Policy describes Our policies and procedures on the
					collection, use and disclosure of Your information when You use the
					Service and tells You about Your privacy rights and how the law
					protects You.
				</small>
				<small>
					We use Your Personal data to provide and improve the Service. By using
					the Service, You agree to the collection and use of information in
					accordance with this Privacy Policy. This Privacy Policy has been
					created with the help of the{' '}
					<a
						href='https://www.termsfeed.com/privacy-policy-generator/'
						rel='nofollow'>
						Privacy Policy Generator
					</a>
					.
				</small>
				<h4 className='my-4'>Interpretation and Definitions</h4>
				<h5 className='my-4'>Interpretation</h5>
				<small>
					The words of which the initial letter is capitalized have meanings
					defined under the following conditions. The following definitions
					shall have the same meaning regardless of whether they appear in
					singular or in plural.
				</small>
				<h5 className='my-4'>Definitions</h5>
				<small>For the purposes of this Privacy Policy:</small>
				<ul>
					<li>
						<small>
							<strong>Account</strong> means a unique account created for You to
							access our Service or parts of our Service.
						</small>
					</li>
					<li>
						<small>
							<strong>Company</strong> (referred to as either &quot;the
							Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
							in this Agreement) refers to Ilamurugu &amp; Associates.
						</small>
					</li>
					<li>
						<small>
							<strong>Cookies</strong> are small files that are placed on Your
							computer, mobile device or any other device by a website,
							containing the details of Your browsing history on that website
							among its many uses.
						</small>
					</li>
					<li>
						<small>
							<strong>Country</strong> refers to: Tamil Nadu, India
						</small>
					</li>
					<li>
						<small>
							<strong>Device</strong> means any device that can access the
							Service such as a computer, a cellphone or a digital tablet.
						</small>
					</li>
					<li>
						<small>
							<strong>Personal Data</strong> is any information that relates to
							an identified or identifiable individual.
						</small>
					</li>
					<li>
						<small>
							<strong>Service</strong> refers to the Website.
						</small>
					</li>
					<li>
						<small>
							<strong>Service Provider</strong> means any natural or legal
							person who processes the data on behalf of the Company. It refers
							to third-party companies or individuals employed by the Company to
							facilitate the Service, to provide the Service on behalf of the
							Company, to perform services related to the Service or to assist
							the Company in analyzing how the Service is used.
						</small>
					</li>
					<li>
						<small>
							<strong>Usage Data</strong> refers to data collected
							automatically, either generated by the use of the Service or from
							the Service infrastructure itself (for example, the duration of a
							page visit).
						</small>
					</li>
					<li>
						<small>
							<strong>Website</strong> refers to Ilamurugu &amp; Associates,
							accessible from{' '}
							<a href='https://ilamsca.com' rel='nofollow'>
								https://ilamsca.com
							</a>
						</small>
					</li>
					<li>
						<small>
							<strong>You</strong> means the individual accessing or using the
							Service, or the company, or other legal entity on behalf of which
							such individual is accessing or using the Service, as applicable.
						</small>
					</li>
				</ul>
				<h4 className='my-4'>Collecting and Using Your Personal Data</h4>
				<h5 className='my-4'>Types of Data Collected</h5>
				<h6 className='my-2'>Personal Data</h6>
				<small>
					While using Our Service, We may ask You to provide Us with certain
					personally identifiable information that can be used to contact or
					identify You. Personally identifiable information may include, but is
					not limited to:
				</small>
				<ul>
					<li>
						<small>Email address</small>
					</li>
					<li>
						<small>First name and last name</small>
					</li>
					<li>
						<small>Phone number</small>
					</li>
					<li>
						<small>Address, State, Province, ZIP/Postal code, City</small>
					</li>
					<li>
						<small>Usage Data</small>
					</li>
				</ul>
				<h6 className='my-2'>Usage Data</h6>
				<small>
					Usage Data is collected automatically when using the Service.
				</small>
				<small>
					Usage Data may include information such as Your Device's Internet
					Protocol address (e.g. IP address), browser type, browser version, the
					pages of our Service that You visit, the time and date of Your visit,
					the time spent on those pages, unique device identifiers and other
					diagnostic data.
				</small>
				<small>
					When You access the Service by or through a mobile device, We may
					collect certain information automatically, including, but not limited
					to, the type of mobile device You use, Your mobile device unique ID,
					the IP address of Your mobile device, Your mobile operating system,
					the type of mobile Internet browser You use, unique device identifiers
					and other diagnostic data.
				</small>
				<small>
					We may also collect information that Your browser sends whenever You
					visit our Service or when You access the Service by or through a
					mobile device.
				</small>
				<h6 className='my-2'>Tracking Technologies and Cookies</h6>
				<small>
					We use Cookies and similar tracking technologies to track the activity
					on Our Service and store certain information. Tracking technologies
					used are beacons, tags, and scripts to collect and track information
					and to improve and analyze Our Service. The technologies We use may
					include:
				</small>
				<dl>
					<dt>
						<small>Cookies or Browser Cookies</small>
					</dt>{' '}
					<dd>
						<small>
							A cookie is a small file placed on Your Device. You can instruct
							Your browser to refuse all Cookies or to indicate when a Cookie is
							being sent. However, if You do not accept Cookies, You may not be
							able to use some parts of our Service. Unless you have adjusted
							Your browser setting so that it will refuse Cookies, our Service
							may use Cookies
						</small>
					</dd>
					<dt>
						<small>Flash Cookies:</small>
					</dt>{' '}
					<dd>
						<small>
							Certain features of our Service may use local stored objects (or
							Flash Cookies) to collect and store information about Your
							preferences or Your activity on our Service. Flash Cookies are not
							managed by the same browser settings as those used for Browser
							Cookies. For more information on how You can delete Flash Cookies,
							please read &quot;Where can I change the settings for disabling,
							or deleting local shared objects?&quot; available at{' '}
							<a
								href='https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_'
								rel=' nofollow '>
								https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
							</a>
						</small>
					</dd>
					<dt>
						<small>Web Beacons.</small>
					</dt>{' '}
					<small>
						Certain sections of our Service and our emails may contain small
						electronic files known as web beacons (also referred to as clear
						gifs, pixel tags, and single-pixel gifs) that permit the Company,
						for example, to count users who have visited those pages or opened
						an email and for other related website statistics (for example,
						recording the popdlarity of a certain section and verifying system
						and server integrity).
					</small>
				</dl>
				<small>
					Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
					Persistent Cookies remain on Your personal computer or mobile device
					when You go offline, while Session Cookies are deleted as soon as You
					close Your web browser. You can learn more about cookies here:{' '}
					<a
						href='https://www.termsfeed.com/privacy-policy-generator/#faq-8'
						rel='nofollow'>
						Cookies by TermsFeed Generator
					</a>
					.
				</small>
				<small>
					We use both Session and Persistent Cookies for the purposes set out
					below:
				</small>
				<ul>
					<li>
						<small>
							<strong>Necessary / Essential Cookies Type:</strong>
						</small>
						<small> Session Cookies</small>
						<small>Administered by: Us</small>
						<small>
							Purpose: These Cookies are essential to provide You with services
							available through the Website and to enable You to use some of its
							features. They help to authenticate users and prevent fraudulent
							use of user accounts. Without these Cookies, the services that You
							have asked for cannot be provided, and We only use these Cookies
							to provide You with those services.
						</small>
					</li>
					<li>
						<small>
							<strong>Cookies Policy / Notice Acceptance Cookies</strong>
						</small>
						<small>Type: Persistent Cookies</small>
						<small>Administered by: Us</small>
						<small>
							Purpose: These Cookies identify if users have accepted the use of
							cookies on the Website.
						</small>
					</li>
					<li>
						<small>
							<strong>Functionality Cookies</strong>
						</small>
						<small>Type: Persistent Cookies</small>
						<small>Administered by: Us</small>
						<small>
							Purpose: These Cookies allow us to remember choices You make when
							You use the Website, such as remembering your login details or
							language preference. The purpose of these Cookies is to provide
							You with a more personal experience and to avoid You having to
							re-enter your preferences every time You use the Website.
						</small>
					</li>
				</ul>
				<small>
					For more information about the cookies we use and your choices
					regarding cookies, please visit our Cookies Policy or the Cookies
					section of our Privacy Policy.
				</small>
				<h5 className='my-4'>Use of Your Personal Data</h5>
				<small>
					The Company may use Personal Data for the following purposes:
				</small>
				<dl>
					<small>
						<dt>To provide and maintain our Service</dt>
						<dd> including to monitor the usage of our Service.</dd>
					</small>

					<small>
						<dt>To manage Your Account:</dt>{' '}
						<dd>
							to manage Your registration as a user of the Service. The Personal
							Data You provide can give You access to different functionalities
							of the Service that are available to You as a registered user.
						</dd>
					</small>

					<small>
						<dt>For the performance of a contract:</dt>
						<dd>
							{' '}
							the development, compliance and undertaking of the purchase
							contract for the products, items or services You have purchased or
							of any other contract with Us through the Service.
						</dd>
					</small>

					<small>
						<dt>To contact You:</dt>{' '}
						<dd>
							To contact You by email, telephone calls, SMS, or other equivalent
							forms of electronic communication, such as a mobile application's
							push notifications regarding updates or informative communications
							related to the functionalities, products or contracted services,
							including the security updates, when necessary or reasonable for
							their implementation.
						</dd>
					</small>

					<small>
						<dt>To provide You</dt>
						<dd>
							{' '}
							with news, special offers and general information about other
							goods, services and events which we offer that are similar to
							those that you have already purchased or enquired about unless You
							have opted not to receive such information.
						</dd>
					</small>

					<small>
						<dt>To manage Your requests:</dt>
						<dd> To attend and manage Your requests to Us.</dd>
					</small>

					<small>
						<dt>For business transfers:</dt>
						<dd>
							{' '}
							We may use Your information to evaluate or conduct a merger,
							divestiture, restructuring, reorganization, dissolution, or other
							sale or transfer of some or all of Our assets, whether as a going
							concern or as part of bankruptcy, liquidation, or similar
							proceeding, in which Personal Data held by Us about our Service
							users is among the assets transferred.
						</dd>
					</small>

					<small>
						<dt>For other purposes:</dt>
						<dd>
							{' '}
							We may use Your information for other purposes, such as data
							analysis, identifying usage trends, determining the effectiveness
							of our promotional campaigns and to evaluate and improve our
							Service, products, services, marketing and your experience.
						</dd>
					</small>
				</dl>
				<small>
					We may share Your personal information in the following situations:
				</small>
				<dl>
					<small>
						<dt>With Service Providers:</dt>{' '}
						<dd>
							{' '}
							We may share Your personal information with Service Providers to
							monitor and analyze the use of our Service, to contact You.
						</dd>
					</small>

					<small>
						<dt>For business transfers:</dt>{' '}
						<dd>
							We may share or transfer Your personal information in connection
							with, or during negotiations of, any merger, sale of Company
							assets, financing, or acquisition of all or a portion of Our
							business to another company.
						</dd>
					</small>
					<small>
						<dt>With Affiliates:</dt>{' '}
						<dd>
							{' '}
							We may share Your information with Our affiliates, in which case
							we will require those affiliates to honor this Privacy Policy.
							Affiliates include Our parent company and any other subsidiaries,
							joint venture partners or other companies that We control or that
							are under common control with Us.
						</dd>
					</small>
					<small>
						<dt>With business partners:</dt>{' '}
						<dd>
							{' '}
							We may share Your information with Our business partners to offer
							You certain products, services or promotions.
						</dd>
					</small>
					<small>
						<dt>With other users:</dt>{' '}
						<dd>
							{' '}
							when You share personal information or otherwise interact in the
							public areas with other users, such information may be viewed by
							all users and may be publicly distributed outside.
						</dd>
					</small>
					<small>
						<dt>With Your consent:</dt>{' '}
						<dd>
							<dd>
								{' '}
								We may disclose Your personal information for any other purpose
								with Your consent.
							</dd>
						</dd>
					</small>
				</dl>
				<h5 className='my-4'>Retention of Your Personal Data</h5>
				<small>
					The Company will retain Your Personal Data only for as long as is
					necessary for the purposes set out in this Privacy Policy. We will
					retain and use Your Personal Data to the extent necessary to comply
					with our legal obligations (for example, if we are required to retain
					your data to comply with applicable laws), resolve disputes, and
					enforce our legal agreements and policies.
				</small>
				<small>
					The Company will also retain Usage Data for internal analysis
					purposes. Usage Data is generally retained for a shorter period of
					time, except when this data is used to strengthen the security or to
					improve the functionality of Our Service, or We are legally obligated
					to retain this data for longer time periods.
				</small>
				<h5 className='my-4'>Transfer of Your Personal Data</h5>
				<small>
					Your information, including Personal Data, is processed at the
					Company's operating offices and in any other places where the parties
					involved in the processing are located. It means that this information
					may be transferred to — and maintained on — computers located outside
					of Your state, province, country or other governmental jurisdiction
					where the data protection laws may differ than those from Your
					jurisdiction.
				</small>
				<small>
					Your consent to this Privacy Policy followed by Your submission of
					such information represents Your agreement to that transfer.
				</small>
				<small>
					The Company will take all steps reasonably necessary to ensure that
					Your data is treated securely and in accordance with this Privacy
					Policy and no transfer of Your Personal Data will take place to an
					organization or a country unless there are adequate controls in place
					including the security of Your data and other personal information.
				</small>
				<h5 className='my-4'>Disclosure of Your Personal Data</h5>
				<h6 className='my-2'>Business Transactions</h6>
				<small>
					If the Company is involved in a merger, acquisition or asset sale,
					Your Personal Data may be transferred. We will provide notice before
					Your Personal Data is transferred and becomes subject to a different
					Privacy Policy.
				</small>
				<h6 className='my-2'>Law enforcement</h6>
				<small>
					Under certain circumstances, the Company may be required to disclose
					Your Personal Data if required to do so by law or in response to valid
					requests by public authorities (e.g. a court or a government agency).
				</small>
				<h6 className='my-2'>Other legal requirements</h6>
				<small>
					The Company may disclose Your Personal Data in the good faith belief
					that such action is necessary to:
				</small>
				<ul>
					<li>
						<small>Comply with a legal obligation</small>
					</li>
					<li>
						<small>
							Protect and defend the rights or property of the Company
						</small>
					</li>
					<li>
						<small>
							Prevent or investigate possible wrongdoing in connection with the
							Service
						</small>
					</li>
					<li>
						<small>
							Protect the personal safety of Users of the Service or the public
						</small>
					</li>
					<li>
						<small>Protect against legal liability</small>
					</li>
				</ul>
				<h5 className='my-4'>Security of Your Personal Data</h5>
				<small>
					The security of Your Personal Data is important to Us, but remember
					that no method of transmission over the Internet, or method of
					electronic storage is 100% secure. While We strive to use commercially
					acceptable means to protect Your Personal Data, We cannot guarantee
					its absolute security.
				</small>
				<h4 className='my-4'>Children's Privacy</h4>
				<small>
					Our Service does not address anyone under the age of 13. We do not
					knowingly collect personally identifiable information from anyone
					under the age of 13. If You are a parent or guardian and You are aware
					that Your child has provided Us with Personal Data, please contact Us.
					If We become aware that We have collected Personal Data from anyone
					under the age of 13 without verification of parental consent, We take
					steps to remove that information from Our servers.
				</small>
				<small>
					If We need to rely on consent as a legal basis for processing Your
					information and Your country requires consent from a parent, We may
					require Your parent's consent before We collect and use that
					information.
				</small>
				<h4 className='my-4'>Links to Other Websites</h4>
				<small>
					Our Service may contain links to other websites that are not operated
					by Us. If You click on a third party link, You will be directed to
					that third party's site. We strongly advise You to review the Privacy
					Policy of every site You visit.
				</small>
				<small>
					We have no control over and assume no responsibility for the content,
					privacy policies or practices of any third party sites or services.
				</small>
				<h4 className='my-4'>Changes to this Privacy Policy</h4>
				<small>
					We may update Our Privacy Policy from time to time. We will notify You
					of any changes by posting the new Privacy Policy on this page.
				</small>
				<small>
					We will let You know via email and/or a prominent notice on Our
					Service, prior to the change becoming effective and update the
					&quot;Last updated&quot; date at the top of this Privacy Policy.
				</small>
				<small>
					You are advised to review this Privacy Policy periodically for any
					changes. Changes to this Privacy Policy are effective when they are
					posted on this page.
				</small>
				<h4 className='my-4'>Contact</h4>
				<small className='d-block mb-1'>
					If you have any questions about these Terms and Conditions, You can
					contact us
				</small>
				<dl>
					<dt>
						<small>By visiting this page on our website:</small>
					</dt>
					<dd>
						<small>
							<Link to='/contact'>ilamsca.com/contact</Link>
						</small>
					</dd>
					<dt>
						<small>By email:</small>
					</dt>
					<dd>
						<small>
							<a href='mailto:ilams@ilamsca.com'>ilams@ilamsca.com</a>
						</small>
					</dd>
					<dt>
						<small>By phone:</small>
					</dt>
					<dd>
						<small> 7200190475</small>
					</dd>
				</dl>
			</div>
		</Layout>
	);
}

export default Privacypolicy;
